# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- group: "anchore"

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  displayName: Checkout

- script: |
    which docker
    docker build -t anchorectl-azure-test:latest .
  displayName: 'Build Docker Image'

- script: |
    curl -sSfL https://anchorectl-releases.anchore.io/anchorectl/install.sh | sh -s -- -b ${HOME}/.local/bin
    export PATH="${HOME}/.local/bin/:${PATH}"
    docker image ls
    anchorectl version
    env
    anchorectl system status
  displayName: 'Install anchorectl Binary'
