# This workflow checks out code, builds an SBOM for the repository,
# and uploads it to Anchore Enterprise

name: Create and Upload Source SBOM

on:
  ### uncomment if you want to fire on every push
  #push:
  #  branches:
  #    - main
  ### build nightly or whatever period
  #schedule:
  #  - cron: '38 23 */14 * *'
  workflow_dispatch:
    inputs:
      mode:
        description: 'Manual Scan'  
        
jobs:

  create-and-push:
    runs-on: ubuntu-latest
    env:
      ANCHORECTL_URL: ${{ vars.ANCHORECTL_URL }}
      ANCHORECTL_USERNAME: ${{ vars.ANCHORECTL_USERNAME }}
      ANCHORECTL_PASSWORD: ${{ secrets.ANCHORECTL_PASSWORD }}
      # if $APPLICATION does not exist, create it with:
      # anchorectl application add ${APPLICATION}
      APPLICATION: ${{ github.event.repository.name }}
      # if $VERSION does not exist, create it with:
      # anchorectl application version add ${APPLICATION}@${VERSION}
      VERSION: HEAD
      

    steps:
                
    - name: Checkout Code
      uses: actions/checkout@v3
                            
    - name: Install Anchore CLI Tools
      run: |
        curl -sSfL https://anchorectl-releases.anchore.io/anchorectl/install.sh | sh -s -- -b ${HOME}/.local/bin v1.7.0
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b ${HOME}/.local/bin v0.80.0
        export PATH="${HOME}/.local/bin/:${PATH}"
        
    - name: Verify Anchore Ready and Reachable
      run: |
        anchorectl system status 
        
    - name: Generate SBOM and Push to Anchore Enterprise
      run: |
        syft -o json . | anchorectl source add --wait ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}@${GITHUB_SHA:0:7} --application ${APPLICATION}@${VERSION} --from -
        
    - name: Pull Vulnerability List
      run: |
        anchorectl source vulnerabilities ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}@${GITHUB_SHA:0:7} 
            
